import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Header';
import { ReactFlowProvider } from 'react-flow-renderer';
import OverviewFlow from '../components/Flowchart';
import { GetServerSideProps } from 'next';

import styles from '../styles/Home.module.css'

interface IProps {
  project?: Object;
}

const Home: React.FC<IProps> = ({project}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>AED</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main} style={{ width: '100%', height: '100%' }}>
        <ReactFlowProvider>
          <OverviewFlow project={project} />
        </ReactFlowProvider>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home;

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const id = ctx?.params?.id;

  const res = await fetch(
    `${process.env.NEXT_PUBLIC_API_URL}/projetos/${id}`
  );

  const project = await res.json();

  return {
    props: {
      project
    }
  };
}